development:
  adapter: postgresql
  encoding: unicode
  database: microblog_development
  pool: 5
  username: fernando
  password: 316814

test:
  adapter: postgresql
  encoding: unicode
  database: microblog_test
  pool: 5
  username: fernando
  password: 316814

production:
  adapter: postgresql
  encoding: unicode
  database: microblog_production
  pool: 5
  username: fernando
  password: 316814