development:
  adapter: postgresql
  encoding: unicode
  database: microblog_development
  pool: 5
  username: developer
  password: developer

test:
  adapter: postgresql
  encoding: unicode
  database: microblog_test
  pool: 5
  username: developer
  password: developer

production:
  adapter: postgresql
  encoding: unicode
  database: microblog_production
  pool: 5
  username: developer
  password: developer
